version: '3.8'
services:
 app:
  build: .
  image: alex5667/app
  environment:
   - PORT=${PORT}
   - DATABASE_URL=${DATABASE_URL_DOCKER}
  ports:
   - ${PORT}:${PORT}

  volumes:
      - ./logs:/app/logs
      - ./src:/app/src 
  depends_on:
   - db
  restart: always

  networks:
   - my-network

 db:
  build: ./src/prisma-db
  image: alex5667/app-db
  container_name: ${POSTGRES_CONTAINER}
  environment:
   - POSTGRES_PORT=${POSTGRES_PORT}
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DB}
   - POSTGRES_CONTAINER=${POSTGRES_CONTAINER}
  ports:
   - ${POSTGRES_PORT}:${POSTGRES_PORT}
  volumes:
   - db-data:/var/lib/postgresql/data
   - db-logs:/var/log/postgresql
  restart: always

  networks:
  - my-network

volumes:
  db-data:
  db-logs:


networks:
  my-network: 
    driver: bridge